//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jg.UpdateClient.UpdateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.jingge.com/Mes", ConfigurationName="UpdateService.IUpdate")]
    public interface IUpdate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/GetVersion", ReplyAction="http://www.jingge.com/Mes/IUpdate/GetVersionResponse")]
        string[] GetVersion(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/GetFilePack", ReplyAction="http://www.jingge.com/Mes/IUpdate/GetFilePackResponse")]
        byte[] GetFilePack(System.Guid id, long From);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/GetFileSize", ReplyAction="http://www.jingge.com/Mes/IUpdate/GetFileSizeResponse")]
        long GetFileSize(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/HelloWorld", ReplyAction="http://www.jingge.com/Mes/IUpdate/HelloWorldResponse")]
        string HelloWorld(string hello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/GetUpadateContent", ReplyAction="http://www.jingge.com/Mes/IUpdate/GetUpadateContentResponse")]
        string GetUpadateContent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.jingge.com/Mes/IUpdate/GetIsForced", ReplyAction="http://www.jingge.com/Mes/IUpdate/GetIsForcedResponse")]
        bool GetIsForced();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUpdateChannel : jg.UpdateClient.UpdateService.IUpdate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateClient : System.ServiceModel.ClientBase<jg.UpdateClient.UpdateService.IUpdate>, jg.UpdateClient.UpdateService.IUpdate {
        
        public UpdateClient() {
        }
        
        public UpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetVersion(System.Guid id) {
            return base.Channel.GetVersion(id);
        }
        
        public byte[] GetFilePack(System.Guid id, long From) {
            return base.Channel.GetFilePack(id, From);
        }
        
        public long GetFileSize(System.Guid id) {
            return base.Channel.GetFileSize(id);
        }
        
        public string HelloWorld(string hello) {
            return base.Channel.HelloWorld(hello);
        }
        
        public string GetUpadateContent() {
            return base.Channel.GetUpadateContent();
        }
        
        public bool GetIsForced() {
            return base.Channel.GetIsForced();
        }
    }
}
